### ISSUE TITLE
Validate geocoding

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1159]
NK has indicated that as of 2019-08-01 geocoding should be working properly.  We should verify that we're actually getting valid results.

**Comment by phorne-uncharted** [comment]
The geocoding itself appears to be working. The biggest stumbling block is the occasional crash due to goat not being able to connect to the required ES instance. As of now, a timeout can be set after which goat will error if no connection can be established. It still errored when set to 100. Going to try with a big value to confirm it can work, then will see if something better can be done.

**Comment by phorne-uncharted** [comment]
Tried it with 1000 for timeout but somehow got a connection failure at 30 seconds so quite possibly not fixing the right thing or the timeout is not properly implemented.
