### ISSUE TITLE
Text facet empty for filenames

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1222]
Filenames are currently identified as text both in the d3m schema, and by SIMON type inference.  When they initially display as a text facet in the chlorine dataset, the facet is empty.  This likely has something to do with a tokenization or stemming failure in the text summary code in `model/storage/text.go`.

**Comment by karlolsonuc** [comment]
Did some investigation on this - I suspect the issue is that the stemming join in text.go basically returns no results for file names as they don't match anything in the stemming DB. Not sure how we catch this case and work around it as repetitive yet unique file name patterns suggest a successful stem should either look like a categorical (no grouping - each file gets a row,) or produce one group with the single common word or phrase in the filename.
