### ISSUE TITLE
Features that aren't part of the training set can't highlight

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1599]
In the Model Create screen you can highlight using facets for features that have been added to the training set.  but you can't with those that haven't (left most entries on screen).  If feels like you should be able to highlight using them, although the "Exclude" button on the right should be disabled, as you can't use feature that is not in the training set as criteria for excluding other records.  This is probably an investigation initially,  as there may be a specific reason we adopted the behavior we have.

**Comment by YohannParis** [comment]
From what I can gather, is that if we use highlight on available variables, we get some errors on one model (Search 0), but none without highlighting (Search 1).

![Screen Shot 2020-05-13 at 16 49 56](https://user-images.githubusercontent.com/636801/81863834-cc363300-9539-11ea-8986-7edef8e875f7.png)

I need to fix my auto-ml to do more investigating because most of my datasets do not work.
