### ISSUE TITLE
Any summary action results in all summaries being refetched

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1755]
The _complete_ set of feature summaries is being fetched twice any time a facet-related action takes place.  For instance, in the model creation screen, adding or removing a feature will result in ALL feature summaries being fetched twice each time you trigger the action.  Clicking on a facet to highlight will likewise cause all feature summaries to re-fetch twice.  This shouldn't be necessary - once a summary has been fetched in a given view, it shouldn't need to be fetched again.  It should also be noted that facet pagination is no longer serving its intended purpose of managing summary fetches, as the full set of summaries are being fetched constantly.

**Comment by cdbethune** [comment]
It looks like the summary fetches are cached, so for the most part we don't refetch data unnecessarily.  The one outstanding optimization is respecting the current page when we are filtering/highlighting.  When the user filters, it necessarily cause a refetch of facet data as the baseline vs. filter data is computed by the DB.  Paging was originally added to ensure that when filtering takes place, we only need to fetch data for those in the active page.  Otherwise, a filtering action on a dataset with 100 variables results in 100 fetches / updates.

**Comment by karlolsonuc** [comment]
Looking at this, it seems we do nothing to respect the paging query strings anywhere beyond using the information there to reload on to the same page should we hard reload or direct navigate there. I think the approach will be to read the page info of various sorts from the query string to build a filter for the list of variables just before we make the included/excluded variable summary fetches which currently from any path taking that action do no filtering based on the page information in the route. We'll probably want a fall back of no filtering at all in the case of nothing defined rather than no fetches at all.

**Comment by karlolsonuc** [comment]
Ah, I think we don't currently respect that because the variable facets component leans on the full list of summaries existing, so introducing pages into our current caching setup would essentially only pull a page at a time, but that then only displays that singular page of items. Even if you work around to expect the full list variables, the cache hits weird states as things are filtered, added and removed. Sometimes the filter update everything, sometimes they don't as there's a false cache hit.
