### ISSUE TITLE
Add sub-sample warning to import

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1833]
We now have environment variable that will cap the number of rows we allow to be imported - this is mainly to keep the H1B and VORA datasets to a reasonable size for the user eval.  We should probably pop up some type of a warning to indicate that we're limiting the import, although I don't think there's currently channel in place that would let the client know the final size of the imported data vs. the actual.

**Comment by phorne-uncharted** [comment]
The import result now has 2 new fields:
- `sampled` is a boolean flagging if a dataset has been randomly sampled due to row count constraints
- `rowCount` has the count of rows ingested into postgres

These should make it possible to provide useful and accurate feedback to the user in cases where we shrunk the data.

**Comment by cdbethune** [comment]
fixed by #1924
