### ISSUE TITLE
Make predictions data select dialog behave like import

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1837]
The predictions data select dialog seems to be missing of the logic that the import has in terms of validation and user feedback.  The two should be consistent.

**Comment by YohannParis** [comment]
The problem with the prediction data select dialog is that it uses websocket but the back-end is not returning status update for the front-end like the dataset import does.

The goal is to make the prediction data import asynchronous, so that in the future we can manage all async interactions with the back-end without blocking the front-end.

**Comment by cdbethune** [comment]
I think this is worth doing now, as the remote sensing cases are often going to involve processing large datasets.  This may bump up against #1799 as we talk about using the simpler import route there, rather than the socket-based approach we're advocating.

**Comment by YohannParis** [comment]
This is issue is not relevant anymore. The new design will use the import dialog directly.
