### ISSUE TITLE
Debug errors in datasets provided by commercial

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2161]
Richard provided a couple of test datasets that he was unable to process on the staging server.  To improve general robustness we should determine the root cause, and fix if it is a case that can be reasonable handled.

**Comment by phorne-uncharted** [comment]
A couple of PRs handled issues with ingesting the datasets. Specifically, sampling on ingest was incorrectly attempting to use stratified sampling rather than random sampling. The header row for one of the files also had some invisible characters in them that broke the TA2-TA3 interaction with the dataset doc and the header row. Those now get filtered out on ingest. Finally, the previous addition of the variable storage name field had not been propagated to the client properly and led to bad interactions when features had spaces in their names (and other special characters).
