### ISSUE TITLE
Add outlier analytic to UI

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2192]
We're adding server support for finding outliers in data (see #2142).  This will be a new feature setup similar to clusters, but rather than being a categorical "pattern" value, it will be a new boolean feature where True indicates a sample is an outlier, and False flags otherwise.  The integration into the UI should be similar - there should be a new button added to the analytic bar on the right (where we currently have the cluster and feature ranking buttons), and upon hitting "apply", the outlier feature should be added to the dataset.  The outlier boolean column should appear in the table data, and a facet should be made available to allow for filtering/highlighting.

**Comment by YohannParis** [comment]
@cdbethune, I reach a blocking issue about showing the _outliers_ results in the data table (see screenshot)

<img width="977" alt="Screen Shot 2021-02-03 at 14 41 09" src="https://user-images.githubusercontent.com/636801/106799968-e0711180-662d-11eb-8e81-8e24028f18d0.png">

After talking with @phorne-uncharted: I need to add the variable `_outlier`  as `data` instead of `metadata` in the back-end [(as seen in the draft PR)](https://github.com/uncharted-distil/distil/pull/2223/files#diff-ee16c348c0c64ae8395c85acb235ee34c26d1d0ee5a07c13702e350f89abb6daR90)

Phil mentioned that this is not a behaviour we want to be doing, as we do not wish the _outliers_ results to be used for modelling.
