### ISSUE TITLE
Geofacet heatmap incorrect

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2545]
With a dataset that uniformly covers a region around addis ababa, we get an irregular heatmap in the geofacet:

![image](https://user-images.githubusercontent.com/8959554/116270093-caff1580-a74c-11eb-9cbb-1ebb156bc0d8.png)

**Comment by phorne-uncharted** [comment]
This is due to how geobounds are queried. The current approach is to use `INTERSECTS` semantics which will count a polygon that crosses bucket boundary multiple times. The `WITHIN` approach would not count those same polygons.

One way to greatly reduce the overcount and undercount would be to reduce the tile to a point and then use that point in the queries. Points ending up on the boundary of two buckets would then suffer the same fate, but that should be a rare occurrence.
