### ISSUE TITLE
Excludes data fetch is not working properly on Select Screen

### ISSUE THREAD

**Issue by Zac-hills** [uncharted-distil/distil#2624]
How to reproduce:
- Exclude a category value
- Exclude another value from the same category
- Switch to Excluded Samples

**Comment by phorne-uncharted** [comment]
I think as part of this issue, we should define exactly what should be displayed in this view and how the user can interact with the data (highlights and all). Can the user reinclude data? If so, how?

Supporting reinclusion based on a highlighted subset of the excluded data adds complexity due to the nested nature of the highlight in this view, where it captures a subset of the exclusion set. In effect, reincluding the highlight from this view would be done by updating every filter set with `filter AND NOT(highlight)`. One of the issues is that generally speaking, the embedded pipeline filters currently only support exclusions. Now we would have to add support for inclusions, but only for data that is already excluded. This new functionality would require either the handling of inverting filter sets when mapping to primitives, or capturing inclusions filter as subsets of the exclusions filters.

I am not saying it can't be done, but rather that now is maybe not the best time to try and get it all working properly. It may be better to have the exclude view simply display what is currently excluded (not sure if highlighting should be done) and let the user remove some of the exclusion filters already set.
