### ISSUE TITLE
Variable search returns empty in explorer

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2815]
In the image below, I'm using ACLED data.  Search should return a few matches like `EVENT_TYPE`.

![image](https://user-images.githubusercontent.com/8959554/128603631-5ed833c8-b3db-4275-8fb7-3cc5627be149.png)

**Comment by Zac-hills** [comment]
![Peek 2021-08-09 12-20](https://user-images.githubusercontent.com/25306965/128739632-4aaa385d-613c-4b76-aaff-ce19c268565f.gif)
 Might have been fixed in previous PR. Currently on main I am getting this. 
![Peek 2021-08-09 12-20](https://user-images.githubusercontent.com/25306965/128739723-973d00f6-4203-4af0-9784-d0187bbee255.gif)
