### ISSUE TITLE
Facet update

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#3108]
A minor clean up of the facets to make them less text-heavy and reduce button clutter:

![image](https://user-images.githubusercontent.com/8959554/142074327-8a6bc753-f034-4624-ba36-9eb716dfa9b2.png)

**Comment by mj3cheun** [comment]
As far as i can see it is not possible to implement this without making changes to the facets-core code. The reason being that the following line: https://github.com/unchartedsoftware/facets/blob/137a6dbb8246025178bb862e94f546365577f39e/packages/facets-core/src/facet-container/FacetContainer.css#L31
limits the height of the facet header to `20px`. It doesnt appear that this can be changed from the distil side.

How do we want to handle this? The best way to patch facets in my opinion will probably to add a new slot (e.g. `header-content`) which omits the `20px` height specification. Of course we can simply remove the `20px` limit from the existing `header-label` and that will work for distil just as well but it could break things in other codebases using facets. Or perhaps all this is more trouble than the issue is worth.

@cdbethune @Zac-hills

**Comment by mj3cheun** [comment]
WIP

<img width="392" alt="Screen Shot 2021-11-19 at 2 18 35 PM" src="https://user-images.githubusercontent.com/14062458/142679264-ee83fe63-fcae-41db-866d-0db693e3fb02.png">
