### ISSUE TITLE
Excluded samples showing included values when filter applied

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#923]
If you exclude some samples, switch to the excluded samples tab, and then apply a filter, the excluded table will show values that should have been excluded.

Example:

1. Select `196_autoMpg` dataset and set `class` as the target
2. Add `displacement` and `cylinders` as features
3. Exclude `3` from the cylinders feature
4. Go to the excluded features tab - only rows with a `cylinders` value of `3` should be displayed
5. Select the `displacement` feature and adjust the range sliders

At this point, the excluded samples table will be showing rows with any number of cylinders.  The `displacement` range filter should be applied, but it should be applied to the excluded sample set.

**Comment by kbirk** [comment]
There are a few things to consider for this.

Currently we have two mechanics in the create models view. `Filters` and `Highlights`. `Highlights` affect the view of the app only, `filters` are committed to the working training set for the model.

The only way to commit a highlight as a filter is with the `exclude` button, which then inverts the highlight. So `filter == NOT(highlight)`

In the current app the facets and table view display the results of `(filter0 AND filter1 ... AND filterN) AND highlight` and the excluded samples displays everything outside of that via `NOT((filter0 AND filter1 ... AND filterN) AND highlight)`


**Example. **
- **Select "3" cylinders to create a highlight of `3 in "cylinders"`**
- **Exclude it to create a filter of `NOT(3 in "cylinders")`.**
- **Select a displacement range to create highlight of `"displacement" >= X && "displacement" <= Y`**

The **"Samples to Model From"** displays the results of:

- **`NOT(3 in "cylinders") AND "displacement" >= X && "displacement" <= Y`**

The **"Excluded Samples"** displays the results of:

- **`NOT(NOT(3 in "cylinders") AND "displacement" >= X && "displacement" <= Y)`**

The change for this issue would instead treat the `Excluded Samples` as swapping the working set from the training set to the excluded set. For this example it would be as simple as changing the filter to `NOT((filter0 AND filter1 ... AND filterN)) AND highlight`. However once we introduce the `re-include` method of committing filters we need more expressive filtering query nesting. 

Which is fine, but also misleading its not simply viewing the exluded samples in a table, its changing how the highlights and filters are being applied to that working set. Some ideas:

- Bump the included / excluded tabs to the view level rather than just the table component, making it clear that the user is operating on the working training set or the working excluded set.

- Add an `include` button to make committing highlights to filters more intuitive. A user selects a region, and they either want it in the training set, or not in the training set.

- When in operating on the excluded working set, have the entire view (facets) show the excluded samples rather than included, we could use red instead of blue to make this more obvious.

- Add proper AND / OR nesting in the post params for filters since we currently only AND them. This will allow for the more expressive filtering of the working sets that is required.

**Comment by cdbethune** [comment]
I'll try to get some input from David from this - I looked back at the design slides we were given and it's not clear what the intended behavior is.
